{{- if and (.Values.serviceMonitor.enabled) (.Values.config.backend "prometheus") -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: metrics
    interval: {{ .Values.serviceMonitor.scrapeInterval | default "15s" }}
    path: {{ .Values.config.prometheus.prometheusPath | default "/metrics" }}
{{- end }}
